# -*- coding: utf-8 -*-
"""emen_7029_7104_2026_asg0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bX3Wv6jFC_TahLJyiAXiztZh-WBqTAJ

# Assignment 0

This assignment is optional and is not graded. It contains exercises to make you familiar with `torch`, the most popular deep learning libraries.

If you understand all the concepts, the course will be very easy for you. I urge you to try this assignment without using GPT/DeepSeek. If you cannot complete the assignment on your own, you should read the [`torch`](https://docs.pytorch.org/docs/stable/index.html) documentation until you can complete the assignment. Both libraries have very good documentation. If you get stuck, you should always refer to the documentation.

## Torch Exercises
"""

# ===== TASK 0: RANDOM NUMBER GENERATION =====
import torch
"""
Generate random numbers using the same seed to demonstrate determinism.
Set manual seed and generate tensors to show reproducibility
"""
seed = 0
# Set the manual seed to 0 using torch.manual_seed
print("The random seed is", seed)

# Create a random matrix using torch.randn (2x2)
A = None
print("Matrix A is", A)

# Create another random matrix using torch.randn (2x2) AFTER resetting the seed
# to 0 using manual_seed
A_again = None
print("Matrix A_again is", A_again)

# Generate more random seeds (simulating key splitting)
seed_2, seed_3 = None, None
print("The new random seeds are", seed_2, seed_3)

# Create a different random matrix using seed_2 or seed_3
# with torch.manual_seed
B = None
print("Matrix B is", B)

# When you use the same seed, results are reproducible
# A should be equal to A_again
# Without resetting seed, B should be different
assert torch.allclose(A, A_again, atol=1e-6), "A != A_again, make sure you reset the seed!"
assert not torch.allclose(A, B, atol=1e-6), "A == B, make sure you use different seeds!"
print("Great work, you completed task 0!")

# ===== TASK 1: INITIALIZING TENSORS =====
"""
Learn to create some vectors, matrices, and tensors
"""
# Use torch.zeros to create a 2x2 matrix of zeros
A = None
print("Matrix A is", A)

# Use torch.ones to create a 3x3x3 tensor of ones
B = None
print("Tensor B is", B)

# Create a vector [0, 1, 2, 3] using torch.arange
c = None
print("Vector c is", c)

# Create a matrix [[2, 4], [6, 8]] from a python list
D = None
print("Matrix D is", D)

assert A.shape == (2, 2) and torch.allclose(A, torch.zeros(2,2)), "Matrix A is not correct"
assert B.shape == (3, 3, 3) and torch.allclose(B, torch.ones(3,3,3)), "Tensor B is not correct"
assert torch.allclose(c, torch.tensor([0, 1, 2, 3])), "Vector c is not correct"
assert torch.allclose(D, torch.tensor([[2,4],[6,8]])), "Matrix D is not correct"
print("Great work, you completed task 1!")

# ===== TASK 2: RESHAPING TENSORS =====
"""
Reshaping is used very often. You can call tensor.reshape to change shape
"""
A = torch.arange(8)
# Print the shape of A using the .shape attribute
print("Print the shape of A!")

# Reshape A to to be of shape (4, 2)
A = None
print("Tensor A is", A)

# Reshape A to have 3 dimensions, each with size 2
B = None
print("Tensor B is", B)

assert A.shape == (4, 2), f"Shape {A.shape} is wrong"
assert B.shape == (2, 2, 2), f"Shape {B.shape} is wrong"
print("Great work, you completed task 2!")

# ===== TASK 3: OPERATIONS AND BROADCASTING =====
"""
Be careful with operation dimensions and broadcasting rules!
"""
A = torch.tensor([[0, 2], [3, 0]])
b = torch.tensor([1, 1])

# Compute the matrix-vector product of A and b
c = None
print("Vector c is", c)

# Compute the matrix-vector product of transpose(A) and b
d = None
print("Vector d is", d)

# Compute the matrix-matrix product of A and transpose(A)
E = None
print("Matrix E is", E)

# Compute the elementwise product A and transpose(A)
F = None
print("Matrix F is", F)

# Scale A by 3
G = None
print("Matrix G is", G)

assert c.shape == (2,), f"Wrong shape {c.shape}, should be (2,)"
assert torch.allclose(c, torch.tensor([2, 3])), f"c values {c} != [2, 3]"

assert d.shape == (2,), f"Wrong shape {d.shape}, should be (2,)"
assert torch.allclose(d, torch.tensor([3, 2])), f"d values {d} != [3, 2]"

assert E.shape == (2, 2), f"Wrong shape {E.shape}, should be (2,2)"
assert torch.allclose(E, torch.tensor([[4, 0], [0, 9]])), f"E values incorrect"

assert F.shape == (2, 2), f"Wrong shape {F.shape}, should be (2,2)"
assert torch.allclose(F, torch.tensor([[0, 6], [6, 0]])), f"F values incorrect"

assert G.shape == (2, 2), f"Wrong shape {G.shape}, should be (2,2)"
assert torch.allclose(G, torch.tensor([[0, 6], [9, 0]])), f"G values incorrect"
print("Great work, you completed task 3!")

# ===== TASK 4: INDEXING =====
"""Indexing is critical for debugging and extracting information
"""
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract 9 using indexing A[x]
b = None
print("Scalar b is", b)

# Extract [5,6] using slicing A[x:y]
c = None
print("Vector c is", c)

# Extract [1,4,7] using slicing A[x:y]
d = None
print("Vector d is", d)

assert b.ndim == 0, "b should be scalar"
assert b == 9, "b should be 9"

assert c.shape == (2,), f"c shape {c.shape} != (2,)"
assert torch.allclose(c, torch.tensor([5, 6])), f"c values {c} != [5,6]"

assert d.shape == (3,), f"d shape {d.shape} != (3,)"
assert torch.allclose(d, torch.tensor([1, 4, 7])), f"d values {d} != [1,4,7]"
print("Great work, you completed task 4!")