# -*- coding: utf-8 -*-
r"""emen_7029_7104_2026_asg1_hw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VebK7j4EKZ8N5Ykvxn8OYXgxhDYsYZhe

In this assignment, you will implement linear regression. You have a number of tasks:

1. You must construct the design matrix $\overline{\mathbf{X}}$ (10 points)
2. You must construct the ground truth outputs $\mathbf{y}$ (10 points)
3. Using $\overline{\mathbf{X}}$ and $\mathbf{y}$, you must find the parameters $\mathbf{\theta}$ that minimize the error (10 points)
4. To verify correctness, look at the generated plot and see if your model makes sense (10 points)

After you are successful with the linear model, focus on the nonlinear model

5. Construct a design matrix $\overline{\mathbf{X}}$ that contains polynomial terms (10 points)
6. Find the parameters $\mathbf{\theta}$ that minimize this nonlinear model (10 points)
7. To verify correctness, ensure the plot makes sense (10 points)
8. Test a different number of terms in $\overline{\mathbf{X}}$, and turn in your assignment with the model that you think looks best (10 points)
9. Make sure you also test generalization capability using separate training and testing datasets! (20 points)
"""

# Import libraries and download dataset
import os
import urllib.request

import torch
import pandas as pd
import matplotlib.pyplot as plt

# Match the JAX version's x64 configuration.
torch.set_default_dtype(torch.float64)


url = "https://gist.githubusercontent.com/smorad/82ff16382b43ec09f7aefcaf8799d756/raw/4aa3e79a555e64bd6fa38124e6ae8fc89df47d59/Life_Expectancy_Data.csv"
filename = "Life_Expectancy_Data.csv"
if not os.path.exists(filename):
    urllib.request.urlretrieve(url, filename)

csv = pd.read_csv(filename)
csv = csv.sort_values(by=['Schooling'], ignore_index=True)
# Some rows have NaN...
csv = csv.dropna()
xs = torch.tensor(csv['Schooling'].to_numpy()) # Inputs
print(csv.keys())
ys = torch.tensor(csv['Life_expectancy '].to_numpy()) # Outputs

# Set up the model

def f(design, theta):
  """Given the design matrix and parameters, return the prediction"""
  return design @ theta # The @ symbol means matrix-multiply

r"""We have constructed the model, but we need to find the correct parameters! Your job is to use machine learning to find the parameters `theta_0, theta_1`. Write your code in the following cell. The cell after the following cell will plot your prediction. You can tell if your code is correct by looking at the resulting plot. If the line accurately predicts the trend of points, then it is likely to be correct!

---


"""

# You need to correctly create the design matrix, the label matrix (y)
# Then find the parameters theta

# We can guess some initial parameters (theta_1, theta_0) but we should train them using
# machine learning
theta_0 = 1.0
theta_1 = 40.0
theta = torch.tensor([theta_0, theta_1]).reshape(2, 1)

# Also need to setup the design matrix and y vector
design = torch.arange(xs.numel() * 2, dtype=torch.get_default_dtype()).reshape(-1, 2) # TODO fix me
y = torch.ones((*ys.shape, 1)) # TODO fix me
# Find theta using design and y
theta = theta # TODO fix me

# To help with debugging
cond = torch.linalg.cond(design.T @ design)
if cond > 10**10:
  print(f"Warning: your design matrix is ill-conditioned! condition number: {cond}")

# Now, let's test it for all the inputs
predictions = f(design, theta)

# Now, let's plot our dataset and our model f
plt.scatter(xs, ys)
plt.xlabel('Years in School')
plt.ylabel('Life Expectancy')

# Predict and plot the model
y_hat = f(design, theta)
plt.plot(xs, predictions, color="orange")

plt.show()

r"""Once you get a good linear fit, let's continue. A linear fit work well enough, but it seems like the dynamics between education and life expectancy might be nonlinear. Next, let's extend our linear function so that it becomes nonlinear.

Right now, our fuction is $\theta_0 + \theta_1 x$. What if we used a polynomial like $\theta_0 + \theta_1 x, + \theta_2 x^2 + \dots + \theta_m x^m$ for our function instead. In the next code block, regress the dataset using a nonlinear function.

HINT: You should not need to change `f`, the trick is changing the design matrix.

HINT: The choice of $m$ matters, play around with it until you get a good fit (and a well-conditioned matrix)
"""

# Once you get a good fit, let's continue. A linear function is nice,
# but the data looks like it might not be linear
# Let's try a higher-dimensional polynomial (e.g. W_m x^m, W_(m-1) x^(m-1), ...)
#
# HINT: Think about how you would change the design matrix to handle
# Quadratic, cubic, etc input features
#
# How many powers do you need? Which seems to fit the data best?

design = design # TODO fix me
theta = theta # TODO fix me

# To help with debugging
cond = torch.linalg.cond(design.T @ design)
if cond > 10**15:
  print(f"Warning: your design matrix is ill-conditioned! condition number: {cond}")

# Let's run it for all the inputs
predictions = f(design, theta)

# Now, let's plot our dataset and our model f
plt.scatter(xs, ys)
plt.xlabel('Years in School')
plt.ylabel('Life Expectancy')

# Plot the model
plt.plot(xs, predictions, color="orange")

plt.show()

# Finally, let us repeat the process but using separate train and test sets
# TODO: Construct separate train and test datasets
# Train the model on the train dataset, and evaluate the model on the test dataset
# Plot the results like above, with the train datapoints and the test datapoints as different colors
# Which m provides the best test performance?
